# Generated by Django 4.1.5 on 2023-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primeiroNome", models.CharField(max_length=255)),
                ("ultimoNome", models.CharField(max_length=255)),
                ("cargo", models.CharField(max_length=255)),
                ("salario", models.FloatField()),
                ("dataAdmissao", models.DateField()),
            ],
        ),
    ]
