# Generated by Django 4.1.5 on 2023-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="dataNascimento",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="telefone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
